### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BruceLoozack** [combo23/KeyDropTools#1]
When I open ''keydroptools.exe'' a message  "invalid character 't' in literal true (expecting 'r')" shows up. Can u explain how to fix that?

**Comment by combo23** [comment]
you must have filled out config.json in a wrong way, use some parser to find the error

**Comment by lilkajt** [comment]
@BruceLoozack take a look at the updated readme tutorial. Explains everything in just 5 mins.
