### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by AksharLeo** [combo23/KeyDropTools#2]
![image](https://user-images.githubusercontent.com/19437316/232772836-b04bdf4b-7df8-4809-88e5-d0867dfc2686.png)

**Comment by combo23** [comment]
u have wrong user agent or cookies or both

**Comment by AksharLeo** [comment]
> u have wrong user agent or cookies or both

I rechecked the User Agent from the link provided in the README, it is correct.


I got the cookies from this extension:

https://chrome.google.com/webstore/detail/%E3%82%AF%E3%83%83%E3%82%AD%E3%83%BCjson%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%87%BA%E5%8A%9B-for-puppet/nmckokihipjgplolmcmjakknndddifde?hl=en


I also tried to get cookies from this:
https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg/related


Neither of them worked, it still gives the same error


`"sessions": [
        "/home/<username>/Downloads/KeyDropTools/key-drop.com.cookies.json"
    ],`

**Comment by combo23** [comment]
> `"sessions": [ "/home/<username>/Downloads/KeyDropTools/key-drop.com.cookies.json" ],`

you are not supposed to path to file with cookies but just cookies

**Comment by AksharLeo** [comment]
> check tutorial, its in the READme.md

Thanks for adding it, it works now
