### ISSUE TITLE
  failed while refreshing session 

### ISSUE THREAD

**Issue by n3x042** [combo23/KeyDropTools#5]
RAFFLE_JOINER | 002 | UTILS | failed while refreshing session: 403

how to fix it?

**Comment by combo23** [comment]
wrong cookies, use tutorial

**Comment by aakashalloria007** [comment]
> wrong cookies, use tutorial

Followed the tutorial still getting "failed while refreshing session: 403" was working a few minutes ago. 
No new cookies are issues same cookie stopped working. No change in UserAgent either

**Comment by n3x042** [comment]
failed while fetching raffles: invalid statuscode: 403

**Comment by Takyu1** [comment]
worked for a bit but now same problem

**Comment by combo23** [comment]
keydrop added cloudflare, bot is not working
